version: 0.2
phases:
  install:
    commands:
      - npm install
  build:
    commands:
      - npm run build
      - aws s3 sync dist/ s3://vueui --delete
      - aws cloudfront create-invalidation --distribution-id E3PQHOWSFH2X2D --paths /index.html
